---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.
ansible_become_method: sudo
# Example options
ansible_nas_hostname: punch-server
ansible_nas_timezone: Etc/UTC

nfs_shares_root: /srv/nfs/
samba_shares_root: /srv/samba/

## Enable some applications
homepage_enabled: false
nextcloud_enabled: true

samba_shares:
  - name: public
    comment: "General use, authenticated"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    path: "{{ samba_shares_root }}/public"
    
  - name: backup
    comment: "Backups, authenticated"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    path: "{{ samba_shares_root }}/backup"
    
  - name: media
    comment: "Media"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    path: "{{ samba_shares_root }}/media"
    
  - name: downloads
    comment: "Stuff downloaded"
    path: "{{ downloads_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes    

  - name: movies
    comment: "Movies"
    path: "{{ movies_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
      

  - name: tv
    comment: "TV Episodes"
    path: "{{ tv_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: music
    comment: "Music"
    path: "{{ music_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: podcasts
    comment: "Podcasts"
    path: "{{ podcasts_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: dump
    comment: "File dump"
    path: "{{ samba_shares_root }}/dump"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: games
    comment: "Games"
    path: "{{ samba_shares_root }}/games"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: photos
    comment: "Pictures"
    path: "{{ photos_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: books
    comment: "Books"
    path: "{{ books_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: audiobooks
    comment: "Audiobooks"
    path: "{{ audiobooks_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: comics
    comment: "Comics"
    path: "{{ comics_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: documents
    comment: "Documents"
    path: "{{ documents_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes
    

  - name: code
    comment: "Code"
    path: "{{ code_root }}"
    guest_ok: no
    public: no
    writable: no
    group: samba_users
    write_list: +samba_users
    browseable: yes

docker_home: /srv/docker/home
docker_image_directory: /srv/docker/images
